---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/speakingdigits.com/ibstz/
    - /bin/cp -r * $DEPLOYPATH
  #  - /bin/cp index.html $DEPLOYPATH
  #  - /bin/cp style.css $DEPLOYPATH
