---
deployment:
  tasks:
    - export DEPLOYPATH=/home/statsdec/public_html/speakingdigits.com/ibstz #Add /<sub_folder> if required
    - /bin/cp index.html $DEPLOYPATH
-   - /bin/cp program/index.html $DEPLOYPATH
    - /bin/cp registration/index.html $DEPLOYPATH
    - /bin/cp flyer/index.html $DEPLOYPATH
-   - /bin/cp -R assets $DEPLOYPATH
